"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Hana Aly and Sarojini Malladi, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ha25476
UT EID 2: sdm3993
"""

def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    lst1 = []
    for _ in range(key):
        row = [''] * len(string)
        lst1.append(row)
    rows = 0
    direction = 1

    for col, j in enumerate(string):
        lst1[rows][col] = j
        if rows == 0:
            direction = 1
        if rows == key - 1:
            direction = -1
        rows += direction
    encode = ''
    for rows in lst1:
        for i in rows:
            if i != '':
                encode += i
    return encode

def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    lst1 = []
    for _ in range(key):
        row = [''] * len(string)
        lst1.append(row)
    rows = 0
    direction = 1

    for col in range(len(string)):
        lst1[rows][col]= '*'
        if rows == 0:
            direction = 1
        if rows == key-1:
            direction = -1
        rows += direction

    z = 0
    for row in lst1:
        for c in range(len(string)):
            if z < len(string) and row[c] == '*':
                row[c] = string[z]
                z += 1
    decode = ''
    rows = 0
    direction = 0
    for col in range(len(string)):
        decode +=lst1[rows][col]
        if rows == 0:
            direction = 1
        if rows == key-1:
            direction = -1
        rows += direction 

    return decode

def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    filtered_str = ''
    for i in string:
        if i.isalpha():
            filtered_str += i.lower()
    return filtered_str

def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    s_character = ord(s) - ord('a')
    p_character = ord(p) - ord('a')

    sums = s_character + p_character
    val = sums % 26

    character = chr(val + ord('a'))
    return character

def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    s_character = ord(s) - ord('a')
    p_character = ord(p) - ord('a')

    diff = (s_character - p_character) + 26
    val = diff % 26

    character = chr(val + ord('a'))
    return character

# TODO: implement this function. You may delete this comment after you are done.
def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    lsts = []
    index = 0
    if not string:
        return ''
    if not phrase:
        return string
    for char in string:
        if char.isalpha():
            key = phrase[index % len(phrase)]
            lsts.append(encode_character(key, char))
            index += 1
    return ''.join(lsts)

def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    lsts = []
    index = 0

    if not string:
        return ''
    if not phrase:
        return string
    for char in string:
        if char.isalpha():
            key = phrase[index % len(phrase)]
            lsts.append(decode_character(key, char))
            index += 1
    return ''.join(lsts)

# TODO: implement this function. You may delete this comment after you are done.
def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # encrypt and print the encoded text using rail fence cipher

    # read encoded text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # encrypt and print the encoded text using Vigenere cipher

    # read the encoded text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # decrypt and print the plain text using Vigenere cipher


# Do NOT modify the following code.
if __name__ == "__main__":
    main()
